create table if not exists public.estado_nomina_prestamos (
  id bigint generated by default as identity primary key,
  fecha date not null,
  nombre text not null,
  descripcion text not null,
  seudonimo text,
  correo text not null,
  prestamo numeric(14,2) default 0,
  intereses_10 numeric(14,2) default 0,
  le_queda_por_pagar numeric(14,2) default 0,
  cuota numeric(14,2) default 0,
  int numeric(14,2) default 0,
  abono_capital numeric(14,2) default 0,
  diferencia_sueldo_abono numeric(14,2) default 0,
  total_a_descontar numeric(14,2) default 0,
  saldo_pendiente numeric(14,2) default 0,
  created_at timestamptz default now()
);

create index if not exists idx_estado_nomina_prestamos_nombre on public.estado_nomina_prestamos (nombre);
create index if not exists idx_estado_nomina_prestamos_seudonimo on public.estado_nomina_prestamos (seudonimo);
create index if not exists idx_estado_nomina_prestamos_correo on public.estado_nomina_prestamos (correo);
